dist: bionic

matrix:
  include:
    - language: python
      python: 3.8
      install:
        - python -m pip install -r requirements.txt
      script:
        - python -m flake8 --count setup.py
    - language: ruby
      rvm:
        - 2.7.1
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot README.md
