dist: bionic

matrix:
  include:
    - language: python
      python: 3.8
      install:
        - python -m pip install -r requirements.txt
        - python -m pip install . --upgrade
      script:
        - python -m flake8 --count auto/deploy.py
        - python -m flake8 --count setup.py
        - python -m flake8 --count src/
        - python -m pytest --cov=tuulbachs --cov=tuulcli --cov=tuuldevops --cov=tuulfile --cov=tuulgit --cov=tuulpy --cov=tuulver --cov=tuulyaml tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: ruby
      rvm:
        - 2.7.1
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot README.md
